### ISSUE TITLE
can't access the page after starting the docker

### ISSUE THREAD

**Issue by mbui0327** [guanyou-git/codemirror-react-test#1]
Hi, first of all, thank for the good work here. I have been looking for something like this for quite a while.
One question, after running the docker-compose, I can see that both react and pyls are running (through docker GUI app). 
However when i point my browser to the port where the react is, nothing coming up.
Any suggestion on how to debug this issue?
Thanks.

**Comment by guanyou-git** [comment]
Hmmm, did you point your browser to localhost:3000 ? Do you have any current services that runs on port 3000?

maybe you can share your docker version or docker-compose version (project built using Docker version 20.10.8 and docker-compose version 1.29.2)? 

things for you to try debug include
- looking at the logs of the container with 
1.  $ docker logs react
- execute a curl inside the react container to check if the webpage is being served
2.  $ docker exec react bash -c "curl localhost:3000"

**Comment by mbui0327** [comment]
I have something running at 3000, so I changed the two ports to  3002 (react) and 3001 (pyls) in the docker-compose.yml.
It is working now after I revert the port back to 3000. I should've made the change in package.json as well. My bad. Thanks.

**Comment by mbui0327** [comment]
I have something running at 3000, so I changed the two ports to  3002 (react) and 3001 (pyls) in the docker-compose.yml.
I have run another docker example and it worked fine.

**Comment by mbui0327** [comment]
Ok it is working after I closed my other app running on :3000, and revert the react app to :3000. It seems like something is hardcoded in the code that is using 3000. Thanks.

**Comment by mbui0327** [comment]
Since you are here, I have a question not exactly in the scope of this project but related. 

As you are an expert, do you have any suggestion on how I should implement code suggestion for others custom python packages. For example, if users have some custom class or using 3rd-party packages, how can we we make sure the suggestion work for them too. 

Thanks.

**Comment by guanyou-git** [comment]
Glad that it's working for you! :) 

On implementing custom python packages, it's basically as shared on README, so 
- Custom python files to be added in ./pyls_jsonrpc/custom_module/ to be served by palantir python language server

Essentially, what above means is it's still manual if you just want a easy implementation, you just have to add the custom python packages into the custom_module and re-run $ docker-compose up -d --build pyls? 

So if you're looking at a more automated solution it'll be to have that volume be specified like a mounted drive/persistent volume in kubernetes context, then create API, you may explore FastAPI (https://fastapi.tiangolo.com/) to create endpoints where user can interact with the files in the folder as well as handler to say restart the pyls service 

Else if you're looking at even more stuff like ability to pip install, you may have a service that updates the requirements.txt for the pyls and you'll get those additional docs in the newly installed libraries on the codemirror suggestion.
